> [GET] FIND PRODUCT LIST
CURL -v 'localhost:8080/product/findAllProduct' \
-X 'GET' 

> [POST] CREATE NEW PRODUCT
CURL -v 'localhost:8080/product/createProduct' \
-X 'POST' \
-H 'Content-Type: application/json; charset=utf-8' \
-H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIVUZMSVQiLCJkYXRhIjp7ImlkIjoiNjI1ZDBkYmE4OGNjZDdiYThjYmVhMTFlIiwicm9sZSI6MX0sImlhdCI6MTY1MDI2NTUzMDEyNCwiZXhwIjoxNjUwMzUxOTMwMTI0fQ.oKE8IcL4NE6xhYIKCFuQvc9ae79xRGFWWIG90VU7hsU' \
-d \
'{
    "name": "Bắp Cải Tím Hữu Cơ", 
    "detail": "Bắp cải tím: tên khoa học là Brassica oleracea var capitata ruba là cây bắp cải có màu tím. Xuất xứ từ Địa Trung Hải, hiện nay được trồng rộng rãi khắp thế giới, thích hợp với khí hậu ôn đới và tại Việt Nam bắp cải tím được trồng nhiều ở Đà Lạt.",
    "price": 55000,
    "groupProduct": "62778a117ae6326a77cac533",
    "weight": 2,
    "quantity": 3000,
    "image": ["https://product.hstatic.net/200000423303/product/bap-cai-tim-huu-co_203f203060064cf5a24b9f8e9c352214_grande.jpg"]
}'






